---
- name: Ensure older versions are not present
  package:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: Ensure prerequisite packages are present
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present

- name: Ensure Docker's official GPG key is present
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Ensure Docker's stable repositiory is configured
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Ensure docker-ce is installed
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Ensure default user is part of "docker" group
  user:
    name: '{{ default_ssh_user }}'
    group: docker
    append: yes
